version: "3.8"

services:
  # API Gateway should be the entry point and can depend on other services
  api-gateway:
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "8085:8085"
    volumes:
      - ./keycloak.crt:/app/config/keycloak.crt
    depends_on:
      - iot-service
      - log-service
    networks:
      - spring-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # IoT Service shouldn't depend on API Gateway
  iot-service:
    image: agritech-iot:1.0.0
    container_name: iot-service
    ports:
      - "8083:8083"
    networks:
      - spring-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Log Service should be independent
  log-service:
    image: logs:1.0.0
    container_name: log-service
    ports:
      - "8082:8082"
    networks:
      - spring-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  spring-net:
    driver: bridge